# Purpose: Shortcuts for common development commands.
#
# For example:
#
# make up
# make down
# make test
# make logs
# make format
# make migrate
# Instead of everyone remembering long Docker commands.